base:
    seed: &seed 0
model:
    type: Llama
    path: model path
    torch_dtype: auto
calib:
    name: wikitext2
    download: False
    path: calib data path
    n_samples: 1
    bs: 1
    seq_len: 2048
    preproc: wikitext2_gptq
    seed: *seed
eval:
    eval_pos: []
    name: wikitext2
    download: False
    path: eval data path
    bs: 1
    seq_len: 2048
quant:
    method: DGQ
    weight:
        w_1:
            bit: 4
            symmetric: False
            granularity: per_group
            group_size: 128
        w_2:
            bit: 8
            symmetric: True
            granularity: per_channel
    act:
        bit: 8
        symmetric: True
        granularity: per_token
save:
    save_trans: False
    save_path: ./save
