base:
    seed: &seed 42
model:
    type: Opt
    path: model path
    torch_dtype: auto
calib:
    name: pileval
    download: False
    path: calib data path
    n_samples: 128
    bs: 1
    seq_len: 2048
    preproc: general
    seed: *seed
eval:
    eval_pos: [pretrain, fake_quant]
    name: wikitext2
    download: False
    path: eval data path
    bs: 1
    seq_len: 2048
quant:
    method: OmniQuant
    weight:
        bit: 8
        symmetric: True
        granularity: per_channel
        group_size: -1
        calib_algo: learnable
        ste: True
    act:
        bit: 8
        symmetric: True
        granularity: per_token
        ste: True
    special:
        let: True 
        lwc_lr: 0.01
        let_lr: 0.005
        use_shift: True
        alpha: 0.5
        deactive_amp: True
        epochs: 20
        wd: 0
    quant_out: True
save:
    save_trans: False
    save_path: ./save